#include "export_generator.hpp"
#include "../target.hpp"
#include "../genex_evaluator.hpp"
#include "../CMakeArray.hpp"
#include <cctype>
#include <filesystem>
#include <sstream>

namespace kiln {

Target* find_target_in_context(const ExportContext& ctx, const std::string& name) {
    if (!ctx.all_targets) return nullptr;
    auto it = ctx.all_targets->find(name);
    if (it != ctx.all_targets->end()) return it->second.get();
    if (ctx.target_aliases) {
        auto alias_it = ctx.target_aliases->find(name);
        if (alias_it != ctx.target_aliases->end()) {
            it = ctx.all_targets->find(alias_it->second);
            if (it != ctx.all_targets->end()) return it->second.get();
        }
    }
    return nullptr;
}

// Convert string to uppercase
static std::string to_upper(const std::string& str) {
    std::string result = str;
    for (char& c : result) { c = static_cast<char>(std::toupper(static_cast<unsigned char>(c))); }
    return result;
}

// Generate the IMPORT_PREFIX computation code for install exports
// Resolve a per-target install destination to a path of the form
// "${_IMPORT_PREFIX}/<rel>". Handles three cases the user may have written:
//   - empty → fallback (caller supplies default like "lib")
//   - relative ("lib", "cm-umode/lib") → joined under _IMPORT_PREFIX
//   - absolute ("/opt/et/cm-umode/lib") → stripped down to the install_prefix
//     so ${_IMPORT_PREFIX} substitutes for the prefix portion at consume time.
//     If the absolute path doesn't sit under install_prefix we leave it alone.
static std::string resolve_install_dest_under_prefix(const std::string& dest, const std::string& fallback,
                                                     const std::string& install_prefix) {
    std::string raw = dest.empty() ? fallback : dest;
    if (raw.empty()) return std::string{};
    if (raw.front() != '/') { return std::string("${_IMPORT_PREFIX}/") + raw; }
    if (!install_prefix.empty()) {
        std::error_code ec;
        auto rel = std::filesystem::relative(raw, install_prefix, ec);
        if (!ec && !rel.empty() && rel.native().rfind("..", 0) != 0) { return std::string("${_IMPORT_PREFIX}/") + rel.generic_string(); }
    }
    return raw; // outside the install tree — emit verbatim
}

static std::string generate_import_prefix_code(const std::string& destination, const std::string& install_prefix = {}) {
    std::ostringstream ss;

    // Compute the destination's depth *relative to the install prefix*. If the
    // user passed an absolute DESTINATION (e.g. "${CMAKE_INSTALL_PREFIX}/lib/..."),
    // counting raw path segments overshoots — we'd walk past the prefix and
    // end up at "/", landing libraries at "/lib/foo.so" instead of
    // "${prefix}/lib/foo.so".
    std::filesystem::path dest_path(destination);
    std::filesystem::path rel_path = dest_path;
    if (dest_path.is_absolute() && !install_prefix.empty()) {
        std::filesystem::path prefix_path(install_prefix);
        std::error_code ec;
        auto rel = std::filesystem::relative(dest_path, prefix_path, ec);
        if (!ec && !rel.empty() && rel.native().rfind("..", 0) != 0) { rel_path = rel; }
    }
    int depth = 0;
    for (const auto& part : rel_path) {
        if (!part.empty() && part != ".") { depth++; }
    }

    // First, get the directory containing this file
    ss << "get_filename_component(_IMPORT_PREFIX \"${CMAKE_CURRENT_LIST_FILE}\" PATH)\n";

    // Navigate up to the install prefix
    for (int i = 0; i < depth; ++i) { ss << "get_filename_component(_IMPORT_PREFIX \"${_IMPORT_PREFIX}\" PATH)\n"; }

    // Verify we ended up at a valid path
    ss << "if(_IMPORT_PREFIX STREQUAL \"/\")\n";
    ss << "  set(_IMPORT_PREFIX \"\")\n";
    ss << "endif()\n";

    return ss.str();
}

namespace {

// Generate CMake header with version check and policy management
std::string generate_cmake_header() {
    std::ostringstream ss;
    ss << "# Generated by kiln - do not edit\n\n";

    // CMake version check
    ss << "if(CMAKE_VERSION VERSION_LESS \"3.5\")\n";
    ss << "  message(FATAL_ERROR \"CMake >= 3.5 required for this export file\")\n";
    ss << "endif()\n\n";

    // Policy management
    ss << "cmake_policy(PUSH)\n";
    ss << "cmake_policy(VERSION 3.5)\n\n";

    // Import file version
    ss << "set(CMAKE_IMPORT_FILE_VERSION 1)\n\n";

    return ss.str();
}

// Generate expected targets check to protect against multiple inclusion
std::string generate_expected_targets_check(const std::vector<Target*>& targets, const std::string& namespace_prefix) {
    std::ostringstream ss;

    // Build list of expected target names
    ss << "# Protect against multiple inclusion\n";
    ss << "set(_cmake_targets_defined \"\")\n";
    ss << "set(_cmake_targets_not_defined \"\")\n";
    ss << "foreach(_cmake_expected_target IN ITEMS";
    for (const auto* t : targets) {
        if (!t || t->get_type() == TargetType::CUSTOM) continue;
        ss << " " << namespace_prefix << t->get_name();
    }
    ss << ")\n";
    ss << "  if(TARGET \"${_cmake_expected_target}\")\n";
    ss << "    list(APPEND _cmake_targets_defined \"${_cmake_expected_target}\")\n";
    ss << "  else()\n";
    ss << "    list(APPEND _cmake_targets_not_defined \"${_cmake_expected_target}\")\n";
    ss << "  endif()\n";
    ss << "endforeach()\n\n";

    // Validation: all defined or all not defined
    ss << "if(_cmake_targets_defined AND _cmake_targets_not_defined)\n";
    ss << "  message(FATAL_ERROR \"Some targets in this export set were already defined\")\n";
    ss << "endif()\n";
    ss << "unset(_cmake_targets_defined)\n";
    ss << "unset(_cmake_targets_not_defined)\n\n";

    return ss.str();
}

// Generate CMake footer with cleanup
std::string generate_cmake_footer() {
    std::ostringstream ss;
    ss << "\n# Cleanup\n";
    ss << "set(CMAKE_IMPORT_FILE_VERSION)\n";
    ss << "cmake_policy(POP)\n";
    return ss.str();
}

// Convert TargetType to the CMake IMPORTED library type string
std::string target_type_to_imported_type(TargetType type) {
    switch (type) {
    case TargetType::EXECUTABLE:
        return "EXECUTABLE";
    case TargetType::SHARED_LIBRARY:
        return "SHARED";
    case TargetType::STATIC_LIBRARY:
        return "STATIC";
    case TargetType::OBJECT_LIBRARY:
        return "OBJECT";
    case TargetType::INTERFACE_LIBRARY:
        return "INTERFACE";
    default:
        return "UNKNOWN";
    }
}

// Escape a string value for CMake syntax (double quotes within quoted strings)
std::string escape_cmake_string(const std::string& str) {
    // Do NOT escape '$' — exported property values are re-evaluated when the
    // generated *Targets.cmake is include()d, so `${_IMPORT_PREFIX}` and
    // friends must reach the consumer un-escaped. Real CMake's exports
    // likewise leave '$' alone here.
    std::string result;
    result.reserve(str.size());
    for (char c : str) {
        if (c == '"' || c == '\\') { result += '\\'; }
        result += c;
    }
    return result;
}

// Format a list of values as a CMake list (semicolon-separated, properly quoted if needed)
std::string format_cmake_list(const std::vector<std::string>& values) {
    std::string result;
    for (size_t i = 0; i < values.size(); ++i) {
        if (i > 0) result += ";";
        result += values[i];
    }
    return result;
}

// Create a GenexEvaluationContext for export evaluation
GenexEvaluationContext make_export_genex_context(const Target* target, const ExportContext& export_ctx) {
    GenexEvaluationContext ctx;
    ctx.build_type = export_ctx.build_type;
    ctx.system_name = export_ctx.system_name;
    ctx.cxx_compiler_id = export_ctx.cxx_compiler_id;
    ctx.c_compiler_id = export_ctx.c_compiler_id;
    ctx.cxx_compiler_version = export_ctx.cxx_compiler_version;
    ctx.c_compiler_version = export_ctx.c_compiler_version;
    ctx.all_targets = export_ctx.all_targets;
    ctx.target_aliases = export_ctx.target_aliases;
    ctx.current_target = target;
    ctx.install_prefix = export_ctx.install_prefix;
    ctx.phase = export_ctx.for_install ? GenexEvaluationContext::Phase::INSTALL : GenexEvaluationContext::Phase::BUILD;
    return ctx;
}

// Evaluate a property list with generator expressions for export
std::vector<std::string> evaluate_export_property(const Target& target, const std::string& prop_name, const ExportContext& export_ctx) {
    // Get the INTERFACE property values
    auto values = target.get_property_list(prop_name, TargetPropertyScope::INTERFACE);
    if (values.empty()) { return {}; }

    auto ctx = make_export_genex_context(&target, export_ctx);
    GenexEvaluator evaluator(ctx);

    auto result = evaluator.evaluate_property_list(values);
    if (!result) {
        // On error, return empty - caller can check target later
        return {};
    }

    return *result;
}

} // anonymous namespace

std::string generate_export_content(const ExportContext& ctx, const std::vector<Target*>& targets) {
    std::ostringstream ss;

    // CMake header with version check and policies
    ss << generate_cmake_header();

    // Expected targets check
    ss << generate_expected_targets_check(targets, ctx.namespace_prefix);

    // For install exports, compute _IMPORT_PREFIX
    if (ctx.for_install && !ctx.destination.empty()) {
        ss << "# Compute the installation prefix relative to this file\n";
        ss << generate_import_prefix_code(ctx.destination, ctx.install_prefix);
        ss << "\n";
    }

    // Determine config suffix for per-configuration properties
    std::string config = ctx.config.empty() ? ctx.build_type : ctx.config;
    if (config.empty()) {
        config = "Debug"; // Default fallback
    }
    std::string config_suffix = "_" + to_upper(config);
    std::string config_upper = to_upper(config);

    // Build a set of exported target names for internal reference checking
    std::set<std::string> exported_names;
    for (const auto* target : targets) { exported_names.insert(target->get_name()); }

    // Generate IMPORTED target definitions
    for (const auto* target : targets) {
        if (!target) continue;

        std::string target_name = target->get_name();
        std::string exported_name = ctx.namespace_prefix + target_name;
        TargetType type = target->get_type();

        // Skip CUSTOM targets - they can't be exported
        if (type == TargetType::CUSTOM) { continue; }

        std::string import_type = target_type_to_imported_type(type);

        // Check if target already exists (allow re-definition in certain cases)
        ss << "# Create imported target " << exported_name << "\n";
        ss << "if(NOT TARGET " << exported_name << ")\n";

        if (type == TargetType::INTERFACE_LIBRARY) {
            ss << "  add_library(" << exported_name << " INTERFACE IMPORTED)\n";
        } else if (type == TargetType::EXECUTABLE) {
            ss << "  add_executable(" << exported_name << " IMPORTED)\n";
        } else {
            ss << "  add_library(" << exported_name << " " << import_type << " IMPORTED)\n";
        }

        ss << "endif()\n\n";

        // Set IMPORTED_CONFIGURATIONS first (for non-interface targets)
        if (type != TargetType::INTERFACE_LIBRARY) {
            ss << "set_property(TARGET " << exported_name << " APPEND PROPERTY IMPORTED_CONFIGURATIONS " << config_upper << ")\n\n";
        }

        // Set target properties
        ss << "set_target_properties(" << exported_name << " PROPERTIES\n";

        // IMPORTED_LOCATION_<CONFIG> (for non-interface targets)
        if (type != TargetType::INTERFACE_LIBRARY) {
            std::string location;
            if (ctx.for_install) {
                // Resolve from the install(TARGETS) destinations the user
                // actually wrote — hard-coding lib/ misplaces artifacts when
                // the project picked a non-default destination (cm-umode does).
                std::string output_name = target->get_output_name();
                auto dit = ctx.target_install_dests.find(target->get_name());
                const auto* d = (dit != ctx.target_install_dests.end()) ? &dit->second : nullptr;

                if (type == TargetType::EXECUTABLE) {
                    std::string dir = resolve_install_dest_under_prefix(d ? d->runtime_dest : std::string{}, "bin", ctx.install_prefix);
                    if (!dir.empty()) location = dir + "/" + output_name;
                } else if (type == TargetType::SHARED_LIBRARY) {
                    std::string dir = resolve_install_dest_under_prefix(d ? d->library_dest : std::string{}, "lib", ctx.install_prefix);
                    if (!dir.empty()) location = dir + "/lib" + output_name + ".so";
                } else if (type == TargetType::STATIC_LIBRARY) {
                    std::string dir = resolve_install_dest_under_prefix(d ? d->archive_dest : std::string{}, "lib", ctx.install_prefix);
                    if (!dir.empty()) location = dir + "/lib" + output_name + ".a";
                } else if (type == TargetType::OBJECT_LIBRARY) {
                    // Object libraries are trickier - they have multiple .o files
                    // For now, skip IMPORTED_LOCATION for object libs
                    location = "";
                }
            } else {
                // Build-tree export: use absolute path
                location = target->get_output_path();
            }

            if (!location.empty()) {
                // Use config-specific property name (e.g., IMPORTED_LOCATION_DEBUG)
                ss << "  IMPORTED_LOCATION" << config_suffix << " \"" << escape_cmake_string(location) << "\"\n";
            }
        }

        // INTERFACE_INCLUDE_DIRECTORIES
        auto includes = evaluate_export_property(*target, "INCLUDE_DIRECTORIES", ctx);
        if (!includes.empty()) {
            std::string include_str;
            for (size_t i = 0; i < includes.size(); ++i) {
                if (i > 0) include_str += ";";
                std::string path = includes[i];
                // For install exports, INSTALL_INTERFACE genex commonly yields
                // either a path relative to the install prefix (e.g. "include")
                // or an absolute path that resolves under it (when the user
                // wrote $<INSTALL_INTERFACE:${CMAKE_INSTALL_PREFIX}/include>).
                // Real CMake rewrites both forms to ${_IMPORT_PREFIX}/<rel> so
                // the export stays relocatable. Absolute paths outside the
                // install tree (system includes etc.) pass through unchanged.
                if (ctx.for_install && !path.empty() && path.compare(0, 16, "${_IMPORT_PREFIX}") != 0) {
                    path = resolve_install_dest_under_prefix(path, std::string{}, ctx.install_prefix);
                }
                include_str += path;
            }
            if (!include_str.empty()) { ss << "  INTERFACE_INCLUDE_DIRECTORIES \"" << escape_cmake_string(include_str) << "\"\n"; }
        }

        // INTERFACE_COMPILE_DEFINITIONS
        auto defs = evaluate_export_property(*target, "COMPILE_DEFINITIONS", ctx);
        if (!defs.empty()) { ss << "  INTERFACE_COMPILE_DEFINITIONS \"" << escape_cmake_string(format_cmake_list(defs)) << "\"\n"; }

        // INTERFACE_COMPILE_OPTIONS
        auto opts = evaluate_export_property(*target, "COMPILE_OPTIONS", ctx);
        if (!opts.empty()) { ss << "  INTERFACE_COMPILE_OPTIONS \"" << escape_cmake_string(format_cmake_list(opts)) << "\"\n"; }

        // INTERFACE_LINK_LIBRARIES
        auto libs = evaluate_export_property(*target, "LINK_LIBRARIES", ctx);
        if (!libs.empty()) {
            std::vector<std::string> processed_libs;
            for (const auto& lib : libs) {
                // If this is a target in our export set, apply namespace prefix
                if (exported_names.count(lib)) {
                    processed_libs.push_back(ctx.namespace_prefix + lib);
                } else {
                    // Check if it's a known target (but not in this export)
                    auto* dep_target = find_target_in_context(ctx, lib);
                    if (dep_target) {
                        // It's an internal target not in this export - use as-is
                        // (CMake would require it to be in some export, but we'll be lenient)
                        processed_libs.push_back(lib);
                    } else {
                        // External library or linker flag - use as-is
                        processed_libs.push_back(lib);
                    }
                }
            }
            if (!processed_libs.empty()) {
                ss << "  INTERFACE_LINK_LIBRARIES \"" << escape_cmake_string(format_cmake_list(processed_libs)) << "\"\n";
            }
        }

        // INTERFACE_LINK_DIRECTORIES — relativize like INTERFACE_INCLUDE_DIRECTORIES
        // so install exports stay relocatable. Same set of cases: relative
        // paths get ${_IMPORT_PREFIX}/ prepended; absolute paths under
        // install_prefix get rewritten; paths outside it pass through.
        auto link_dirs = evaluate_export_property(*target, "LINK_DIRECTORIES", ctx);
        if (!link_dirs.empty()) {
            if (ctx.for_install) {
                for (auto& p : link_dirs) {
                    if (!p.empty() && p.compare(0, 16, "${_IMPORT_PREFIX}") != 0) {
                        p = resolve_install_dest_under_prefix(p, std::string{}, ctx.install_prefix);
                    }
                }
            }
            ss << "  INTERFACE_LINK_DIRECTORIES \"" << escape_cmake_string(format_cmake_list(link_dirs)) << "\"\n";
        }

        // INTERFACE_LINK_OPTIONS
        auto link_opts = evaluate_export_property(*target, "LINK_OPTIONS", ctx);
        if (!link_opts.empty()) { ss << "  INTERFACE_LINK_OPTIONS \"" << escape_cmake_string(format_cmake_list(link_opts)) << "\"\n"; }

        // INTERFACE_COMPILE_FEATURES
        auto features = evaluate_export_property(*target, "COMPILE_FEATURES", ctx);
        if (!features.empty()) { ss << "  INTERFACE_COMPILE_FEATURES \"" << escape_cmake_string(format_cmake_list(features)) << "\"\n"; }

        ss << ")\n\n";
    }

    // Cleanup for install exports
    if (ctx.for_install && !ctx.destination.empty()) {
        ss << "# Cleanup temporary variable\n";
        ss << "unset(_IMPORT_PREFIX)\n";
    }

    // CMake footer with policy cleanup
    ss << generate_cmake_footer();

    return ss.str();
}

std::string generate_config_export_content(const ExportContext& ctx, const std::vector<Target*>& targets,
                                           const std::string& install_prefix) {
    std::ostringstream ss;

    // Determine config name
    std::string config = ctx.config.empty() ? ctx.build_type : ctx.config;
    if (config.empty()) { config = "noconfig"; }
    std::string config_upper = to_upper(config);
    std::string config_suffix = "_" + config_upper;

    // Header
    ss << "# Generated by kiln - per-configuration file for " << config_upper << "\n\n";

    // Compute _IMPORT_PREFIX
    if (ctx.for_install && !ctx.destination.empty()) {
        ss << "# Compute the installation prefix relative to this file\n";
        ss << generate_import_prefix_code(ctx.destination, ctx.install_prefix);
        ss << "\n";
    }

    // Build genex evaluator from export context for evaluating target properties
    GenexEvaluationContext genex_ctx;
    genex_ctx.build_type = ctx.build_type;
    genex_ctx.system_name = ctx.system_name;
    genex_ctx.cxx_compiler_id = ctx.cxx_compiler_id;
    genex_ctx.c_compiler_id = ctx.c_compiler_id;
    genex_ctx.cxx_compiler_version = ctx.cxx_compiler_version;
    genex_ctx.c_compiler_version = ctx.c_compiler_version;
    genex_ctx.install_prefix = ctx.install_prefix;
    genex_ctx.all_targets = ctx.all_targets;
    genex_ctx.target_aliases = ctx.target_aliases;
    genex_ctx.phase = GenexEvaluationContext::Phase::INSTALL;

    // For each target, set per-config properties
    for (const auto* target : targets) {
        if (!target) continue;

        std::string target_name = target->get_name();
        std::string exported_name = ctx.namespace_prefix + target_name;
        TargetType type = target->get_type();

        // Skip interface libraries (no per-config properties needed)
        if (type == TargetType::INTERFACE_LIBRARY || type == TargetType::CUSTOM) { continue; }

        // Per-target evaluator for property reads
        auto target_ctx = genex_ctx;
        target_ctx.current_target = target;
        GenexEvaluator eval(target_ctx);

        // Set the imported location for this configuration. Like the main
        // export file, derive the directory from the install(TARGETS)
        // destinations rather than hard-coding lib/ and bin/.
        std::string location;
        auto dit = ctx.target_install_dests.find(target->get_name());
        const auto* d = (dit != ctx.target_install_dests.end()) ? &dit->second : nullptr;

        if (type == TargetType::EXECUTABLE) {
            std::string dir = resolve_install_dest_under_prefix(d ? d->runtime_dest : std::string{}, "bin", ctx.install_prefix);
            if (!dir.empty()) location = dir + "/" + target->get_output_name();
        } else if (type == TargetType::SHARED_LIBRARY) {
            std::string soversion = eval.evaluate_target_property(*target, "SOVERSION");
            std::string version = eval.evaluate_target_property(*target, "VERSION");
            std::string lib_name = "lib" + target->get_output_name() + ".so";
            if (!version.empty()) {
                lib_name += "." + version;
            } else if (!soversion.empty()) {
                lib_name += "." + soversion;
            }
            std::string dir = resolve_install_dest_under_prefix(d ? d->library_dest : std::string{}, "lib", ctx.install_prefix);
            if (!dir.empty()) location = dir + "/" + lib_name;
        } else if (type == TargetType::STATIC_LIBRARY) {
            std::string dir = resolve_install_dest_under_prefix(d ? d->archive_dest : std::string{}, "lib", ctx.install_prefix);
            if (!dir.empty()) location = dir + "/lib" + target->get_output_name() + ".a";
        }

        if (!location.empty()) {
            ss << "# Import target \"" << exported_name << "\" for configuration \"" << config_upper << "\"\n";
            ss << "set_property(TARGET " << exported_name << " APPEND PROPERTY IMPORTED_CONFIGURATIONS " << config_upper << ")\n";
            ss << "set_target_properties(" << exported_name << " PROPERTIES\n";
            ss << "  IMPORTED_LOCATION" << config_suffix << " \"" << location << "\"\n";

            // For shared libs, set SONAME if applicable
            if (type == TargetType::SHARED_LIBRARY) {
                std::string soversion = eval.evaluate_target_property(*target, "SOVERSION");
                std::string version = eval.evaluate_target_property(*target, "VERSION");
                if (!soversion.empty() || !version.empty()) {
                    std::string soname = "lib" + target->get_output_name() + ".so";
                    if (!soversion.empty()) { soname += "." + soversion; }
                    ss << "  IMPORTED_SONAME" << config_suffix << " \"" << soname << "\"\n";
                }
            }
            ss << ")\n\n";
        }
    }

    // Cleanup
    if (ctx.for_install && !ctx.destination.empty()) {
        ss << "# Cleanup temporary variable\n";
        ss << "unset(_IMPORT_PREFIX)\n";
    }

    return ss.str();
}

} // namespace kiln
